# Generated by Django 6.0.4 on 2026-04-22 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('bloco', models.CharField(blank=True, max_length=50)),
                ('numero', models.CharField(max_length=20)),
                ('andar', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'verbose_name': 'Sala',
                'verbose_name_plural': 'Salas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('manutencao', 'Manutencao'), ('inativo', 'Inativo')], default='ativo', max_length=20)),
                ('quantidade_slots', models.PositiveIntegerField(default=10)),
                ('temperatura', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ultima_comunicacao', models.DateTimeField(blank=True, null=True)),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='racks', to='app.sala')),
            ],
            options={
                'verbose_name': 'Rack',
                'verbose_name_plural': 'Racks',
                'ordering': ['identificador'],
            },
        ),
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50, unique=True)),
                ('modelo', models.CharField(max_length=100)),
                ('numero_slot', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('disponivel', 'Disponivel'), ('em_uso', 'Em uso'), ('manutencao', 'Manutencao'), ('ausente', 'Ausente')], default='disponivel', max_length=20)),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True)),
                ('rack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notebooks', to='app.rack')),
            ],
            options={
                'verbose_name': 'Notebook',
                'verbose_name_plural': 'Notebooks',
                'ordering': ['rack', 'numero_slot'],
                'constraints': [models.UniqueConstraint(fields=('rack', 'numero_slot'), name='unique_slot_por_rack')],
            },
        ),
    ]
