# Generated by Django 6.0.4 on 2026-04-23 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_rack_ultima_comunicacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='cpf',
            field=models.CharField(error_messages={'unique': 'Já existe um cadastro com este CPF.'}, max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='tag',
            field=models.CharField(error_messages={'unique': 'Já existe um notebook com esta tag.'}, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='rack',
            name='identificador',
            field=models.CharField(error_messages={'unique': 'Já existe um rack com este identificador.'}, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='rack',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('manutenção', 'Manutenção'), ('inativo', 'Inativo')], default='ativo', max_length=20),
        ),
        migrations.AlterConstraint(
            model_name='notebook',
            name='unique_slot_por_rack',
            constraint=models.UniqueConstraint(fields=('rack', 'numero_slot'), name='unique_slot_por_rack', violation_error_message='Já existe um notebook cadastrado neste slot para este rack.'),
        ),
    ]
