# Generated by Django 6.0.4 on 2026-04-23 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_cadastro_cpf_alter_notebook_tag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='cargo',
            field=models.CharField(choices=[('professor', 'Professor'), ('tutor', 'Tutor'), ('gestor', 'Gestor'), ('aluno', 'Aluno')], help_text='Selecione o cargo', max_length=20, verbose_name='Cargo (professor, tutor, gestor ou aluno)'),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='status',
            field=models.CharField(choices=[('disponivel', 'Disponível'), ('em_uso', 'Em uso'), ('manutencao', 'Manutenção'), ('ausente', 'Ausente')], default='disponivel', max_length=20),
        ),
        migrations.AlterField(
            model_name='rack',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('manutencao', 'Manutenção'), ('inativo', 'Inativo')], default='ativo', max_length=20),
        ),
    ]
